name: svhip
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - clustalw >=2.1.0
  - biopython >=1.79
  - matplotlib-base >=3.5.1
  - blosum >=1.1.3
  - scipy >=1.8.0
  - scikit-learn ==1.1.3
  - seaborn >=0.11.2  